# Generated by Django 5.1.2 on 2024-10-12 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="data_added",
            new_name="date_added",
        ),
    ]
